services:
  frontend:
    image: ${DOCKER_USERNAME}/crm-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}

  backend:
    image: ${DOCKER_USERNAME}/crm-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

