name: Deploy on EC2

on:
  workflow_run:
    workflows: 
      - Build And Test CRM Pipeline
    types:
      - completed
jobs:
  deploy:
    # Deploy only if Build and Test succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: SSH And Deploy on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |

            set -e 

            cd /home/ubuntu/CRM-V2-SerpHawk-main
            
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh

            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts

            ssh -T git@github.com || true

            git pull origin main
            
            docker compose pull

            docker compose up -d

            docker image prune -f

            docker compose ps



