name: Build And Test CRM Pipeline

on: 
  push:
    branches:
      - main

  pull_request:
    branches: 
      - main

permissions:
  id-token: write
  contents: read          

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Dependencies
        run: pip install -r requirements.

      - name: Build Docker Image
        run: docker build -t crm-backend:latest .
      
      - name: Show GitHub OIDC context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Ref name: $GITHUB_REF_NAME"
          echo "Event: $GITHUB_EVENT_NAME"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Image
        run: |
          docker tag crm-backend:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/crm-backend:latest

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/crm-backend:latest

      - name: Run Docker container 
        run: docker run -d --name backend-crm -p 8000:8000 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" crm-backend
     
      - name: Test Backend 
        run: | 
          for i in {1..12}; do 
            if curl --fail http://localhost:8000/health; then 
              echo "Backend is healthy" 
              exit 0 
            fi 
          
            echo "Backend not ready yet... attempt $i/12" 
            sleep 5

          done 
          
          echo "Backend failed health check" 
          exit 1 
      
      - name: Show container Logs if test fails 
        if: failure() 
        run: docker logs backend-crm

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install Frontend Dependencies
        working-directory: frontend 
        run: npm ci
      
      - name: Build Frontend Docker Image 
        run: | 
          docker build -t crm-frontend ./frontend 
      
      - name: Run Frontend Container 
        run: docker run -d --name crm-frontend-test -p 3000:3000 crm-frontend

      - name: Test Frontend
        run: |
          for i in {1..12}; do 
            if curl --fail http://localhost:3000; then 
              echo "Frontend is healthy" 
              exit 0

              fi 
              
              echo "Frontend not ready yet... attempt $i/12" 
              sleep 5 
            done 
            
            echo "Frontend failed health check" 
            exit 1

      - name: Frontend Container Logs
        if: failure()
        run: docker logs crm-frontend-test   
        
      - name: Tag Frontend Image And Push Image
        run: |
          docker tag crm-frontend:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/crm-frontend:latest
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/crm-frontend:latest
  
